# Generated by Django 3.0.6 on 2020-06-02 03:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('phongkham', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='is_doctor',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='staff',
            name='is_doctor',
            field=models.BooleanField(default=False),
        ),
    ]
