# Generated by Django 3.1.1 on 2020-10-09 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('phongkham', '0004_auto_20200927_1011'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='BHYT',
            field=models.CharField(choices=[('BHYT', 'BHYT'), ('KHONG', 'Không có'), ('DICHVU', 'Khám dịch vụ')], default='KHONG', max_length=6),
        ),
    ]
