# Generated by Django 3.1.1 on 2020-10-24 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('phongkham', '0007_auto_20201024_0743'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicine',
            name='price',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
