# Generated by Django 3.1.1 on 2020-10-24 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('phongkham', '0008_medicine_price'),
    ]

    operations = [
        migrations.CreateModel(
            name='Test',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(max_length=200)),
                ('price', models.PositiveIntegerField()),
            ],
        ),
        migrations.AddField(
            model_name='prescription',
            name='fee',
            field=models.PositiveIntegerField(default=37800),
        ),
    ]
