# Generated by Django 3.1.1 on 2020-10-24 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('phongkham', '0009_auto_20201024_1137'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicalrecord',
            name='test_info',
            field=models.ManyToManyField(to='phongkham.Test'),
        ),
    ]
