# Generated by Django 3.1.1 on 2020-10-24 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('phongkham', '0010_medicalrecord_test_info'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicalrecord',
            name='fee',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
