# Generated by Django 3.1.1 on 2020-10-24 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('phongkham', '0011_auto_20201024_1648'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicalrecord',
            name='fee',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='prescription',
            name='fee',
            field=models.PositiveIntegerField(),
        ),
    ]
